set up routes.js, login and signup page but with no functionality yet…
sndadda/cs461 pull request #1
Opened 2024-11-27 04:32 UTC by sndadda

…, added logo and empty sidebar

2024-11-27 05:01 UTC, wc543 requested changes
Everything is good, it is just missing a .gitignore file for node_modules

2024-11-27 05:38 UTC, BensonZhang127 commented
Everything works and looks good to me.

2024-11-28 02:49 UTC, wc543 approved these changes

2024-11-28 02:54 UTC, wc543 approved these changes

2024-11-28 03:01 UTC, merged